### ISSUE TITLE
Inspiration from UBports installer

### ISSUE THREAD

**Issue by MagicLike** [openandroidinstaller-dev/openandroidinstaller#117]
I like how the [UBports](https://github.com/ubports/ubports-installer) installer is transitioning between pages and using animations. Also it has an integrated downloader which might be a nice feature for those who don't want to click through e.g. the Lineage OS downloads, which are sometimes pretty hidden. Also this downloader might be nice for fast downloads of the newest TWRP.

I will just list my ideas here for easier visibility:
- [ ] Animations & transitions?
- [ ] Integrated downloader
  - [ ] for Lineage OS
  - [ ] for Lineage OS for microG
  - [ ] for TWRP
  - [ ] for ...

**Comment by tsterbak** [comment]
I considered an integrated downloader, but I don't think it's worth the effort right now.

On one hand, it creates a slight barrier to run the tool, so people have to do some minimal thinking before they try to flash their devices. You cannot just press all buttons and brick your phone. But the barrier is also not too high, given you already downloaded the OAI.
On the other hand, TWRP does not like automatic downloads or mirrors of their images and I see the point and don't want to mess with it.

While animations are nice, I cannot build them and I think they are not necessary for the tool to work. So that should be postponed for what later.
