### ISSUE TITLE
Add support for `HWLYO-L6735`

### ISSUE THREAD

**Issue by chisumarius** [openandroidinstaller-dev/openandroidinstaller#389]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Huawei

### Name

LYO-L21

### Device code

LYO-L21

### Model

LYO-L21

### Device images

```Markdown
LINEAGE OS
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
Just help with bootloader unlock also
ALL THE BEST
```

**Comment by tsterbak** [comment]
Hey, thanks for your interest in the project :)
It's very unlikely, that this device will ever be supported, since Huawei stopped to allow unlocking the bootloader. And we only support with official unlocking procedures as much as we can.
If you think differently, let me know, and maybe we can help :)
Good luck
