### ISSUE TITLE
Add support for `oppo A54`

### ISSUE THREAD

**Issue by Thomaspacchia** [openandroidinstaller-dev/openandroidinstaller#526]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

oppo

### Name

A54

### Device code

4SORTGJJLRZTHQ4

### Model

CHP2239

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by Thomaspacchia** [comment]
please provide affect software for this device

**Comment by anon1892** [comment]
> please provide affect software for this device

What?

As far I know, Oppo don't let users unlock their bootloader, so they can't install custom ROM on Oppo devices.
In your specific case, you have a MediaTek SoC, and a security breach allows you to unlock the bootloader (see [here](https://xdaforums.com/t/cph2239-how-to-unlock-bootloader-and-root-the-oppo-a54.4396001/)), only if you are on an old version of the OS.

Anyway, there is no development for this device (because of Oppo bootloader unlock policy...), so if you really want to install a custom ROM, look at GSIs (see [here](https://github.com/phhusson/treble_experimentations/wiki)), but they are usually less stable than device specific build.

Also, OpenAndroidInstaller do not support GSI install, and it's not on the roadmap afaik.
