### ISSUE TITLE
Add support for `HWCAM-H`

### ISSUE THREAD

**Issue by kotekiipsotek** [openandroidinstaller-dev/openandroidinstaller#537]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

huawei

### Name

cam-L21

### Device code

asdfas

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Hello, thanks for your interest in this project!
Huawei doesn't allow bootloader unlocking anymore (since 2017 or so)
Without the ability to unlock the bootloader, one cannot install custom ROM.

**Comment by kotekiipsotek** [comment]
Yes I know. But there are websites where you can buy an unlock code. I also
have an unlocked phone, but I have a problem with fastboot. I posted here
and after a few days of searching and thinking, I managed to unblock
it. Although
I don't know how, exactly. Did the link in the last post work or was it
something else?
https://www.linuxquestions.org/questions/linux-mobile-81/unlock-phone-fastboot-4175737077/
I'm
currently thinking about how to upload TWRP, because Fastboot doesn't see
my device, and then try another system with a newer Android, because some
of the applications I care about no longer support Android 6.0.

niedz., 2 cze 2024 o 21:02 anon1892 ***@***.***> napisał(a):

**Comment by anon1892** [comment]
If adb and fastboot are misconfigured on your computer, yes, managing udev rules may correct it.
Alternatively, you can use Ubuntu (or others distributions, but I've tried with Ubuntu) and just type the following in a terminal : 
```bash
sudo apt install adb fastboot
```
and everything should be good.

I'm not sure if websites selling unlock codes are legit/working...
And if your device is unlocked, you will have to install GSI to have a recent Android version. Note that GSIs are not supported by OpenAndroidInstaller, and since they are not developed specifically for your device, you may expect bugs.
